version: '3'

services:
  mysql:
    image: mysql
    # Leave commented for local docker network ONLY access, if uncommented it'll be locally accesible at port 3306
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTpassword
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local

  phpmyadmin:
    # The password of the 'root' user will be the same as MYSQL_ROOT_PASSWORD env var in mysql container
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - local

volumes:
  mysql_data:
networks:
  local: